main: ale444113.anticheat.AntiCheat
version: 0.2
name: AntiCheat
description: Es un simple plugin creado por diversion.
author: ale444113
permissions:
  anticheat.warnings:
    description: Este permiso le da las alertas a los moderadores
    default: false
  anticheat.reload:
    description: Este permiso permite que recargue el plugin
    default: false
commands:
  anticheat:
    description: Da info y permite recargar el anticheat